# SConscript - build glutils under Linux

SOURCE = "glutil.cpp OBJModel.cpp";
TARGET = "libGLUTIL"

Import( "env" );

from SCript.Stages import build;

libGLUTIL = None;

@build
def build_lab():
	obj = [env.Object(src) for src in SOURCE.split()];
	lib = env.StaticLibrary( target = TARGET, source = obj );

	global libGLUTIL;
	libGLUTIL = lib;

	return lib; 

Return( "libGLUTIL" );

# EOF vim:syntax=python:foldmethod=marker:ts=4:noexpandtab
