/*
 * This file is part of Bubba-3D.
 *
 * Bubba-3D is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Bubba-3D is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Bubba-3D. If not, see http://www.gnu.org/licenses/.
 */
#pragma once

#include "linmath/float3.h"
#include "linmath/Quaternion.h"

#define PARTICLE_SPEED ((rand() % 6000) - 3000.0f) / 5000.0f
#define PARTICLE_LIFE 1000.0f + (rand() % 1000)

class ParticleConf;

/**
 * \breif Represents a particle generated by a ParticleGenerator.
 *
 */
class Particle {

public:
    Particle(ParticleConf &conf, chag::float4x4 modelMatrix);

    /**
     * Resets the particle according to the given ParticleConf.
     * This is used in order to reuse particles.
     * @param conf The ParticleConf to used by the ParticleGenerator.
     */
    void reset( ParticleConf &conf, chag::float4x4 modelMatrix);

    /**
     * @return If the Particle is alive, that is visible, or not.
     *         Dead Particles will can be reused by calling reset().
     */
    bool isAlive();

    /**
     * @param deltaTime Time since last update in seconds.
     * @param distanceToCam The distance from camera in units.
     * @param conf The ParticleConf used by the ParticleGenerator.
     */
    void update(float deltaTime, float distanceToCam, ParticleConf &conf);
    chag::float3 getPosition();

private:
    float life; //in ms
    chag::float3 position;
    chag::float3 velocity;
};
