#ifndef BUBBA_3D_CONSTANTS_H
#define BUBBA_3D_CONSTANTS_H

#define UNIFORM_BUFFER_OBJECT_MATRICES_NAME "Matrices"
#define UNIFORM_BUFFER_OBJECT_MATRICES_INDEX 0


#define SIMPLE_SHADER_NAME "simple_shader"



#endif //BUBBA_3D_CONSTANTS_H
